- hosts: all
  become: true
  vars_files:
    - vars.yml
  strategy: free

  tasks:
    - name: Add google signing key
      apt_key: url=https://packages.cloud.google.com/apt/doc/apt-key.gpg

    - name: Add the k8s apt repository
      apt_repository: repo='deb http://apt.kubernetes.io/ kubernetes-xenial main'

    - name: Install packages
      apt: name={{ item }} state=installed update_cache=true force=no
      with_items: "{{ PACKAGES }}"
